swagger: "2.0" 
info:
  description: "Public documentation for payment & subscription System"
  version: "1.0.0"
  title: "Payment & Subscription API"
  contact:
    email: "team@example.com"
host: "api.payments.com"
schemes:
  - "http"
paths:
  /users:
    get:
      summary: "Return details about all users"
      operationId: "getUsers"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Users"
        "400":
          description: "bad request"
        "404":
          description: "users not found"
definitions:
  User:
    type: "object"
    properties: 
      id: 
        type: "integer"
        format: "int64"
      username:
        type: "string"
      subscriptionStatus:
        type: "boolean"
      subscriptionType:
        type: "string"
      email:
        type: "string"
  Users: 
    type: "array"
    items:
      $ref: "#/definitions/User"
  ApiResponse:
    type: "object"
    properties: 
      code:
        type: "integer"
        format: "i32"
      type:
        type: "string"
      message:
        type: "string"